import type { InstanceInfo } from "@/hooks/useEvaluationData";
import { getStatus, InstanceStatus } from "@/lib/execution";
import type { IntentInstance } from "@/model/model";
import { finalizeDraft, updateDraft } from "@/services/chatService";
import { setMessageScore } from "@/services/messageService";
import { MESSAGE_SCORE_MISSING } from "@/utils/constants";
import { getLastMessage } from "@/utils/message";
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuSeparator, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from "@/components/ui/context-menu";
import type { ToastProps } from "@/components/ui/toast";
import { useToast } from "@/components/ui/use-toast";
import { BookTextIcon, ClipboardCopyIcon, FileLineChartIcon, LinkIcon, RotateCcwIcon, ScrollTextIcon } from "lucide-react";
import { useCallback } from "react";
import { generatePlantUMLLink, getPlantUML } from "@/lib/plantuml";

export type ContextMenuInstanceProps = {
    instance: IntentInstance;
    data: InstanceInfo;
    forceReload: () => void;
    children?: React.ReactNode;
}
type ToasterToast = ToastProps & {
    id: string
    title?: React.ReactNode
    description?: React.ReactNode
}
type Toast = Omit<ToasterToast, "id">


const reEvaluateInstance = async (instance: IntentInstance): Promise<[boolean, null | Toast]> => {
    const [lastChat, lastIteration, lastMessage] = getLastMessage(instance)
    if (!lastChat) return [false, {
        title: "Invalid re-evaluation",
        description: "The instance has no chat",
        variant: "destructive"
    }]
    if (!lastIteration) return [false, {
        title: "Invalid re-evaluation",
        description: "The last chat has no iteration",
        variant: "destructive"
    }]
    if (!lastMessage) return [false, {
        title: "Invalid re-evaluation",
        description: "The last iteration has no message",
        variant: "destructive"
    }]

    if (!(`score` in lastMessage)) {
        return [false, {
            title: "Invalid re-evaluation",
            description: "The last message was not generated by the AI",
            variant: "destructive"
        }]
    }

    await setMessageScore(lastMessage.id, { score: MESSAGE_SCORE_MISSING })
    await finalizeDraft(lastChat?.id, false)
    await updateDraft(lastChat.id, {
        actualNode: lastIteration.type,
    })

    return [true, null]
}

export const ContextMenuInstance = ({ instance, data, forceReload, children }: ContextMenuInstanceProps) => {
    const { toast } = useToast()
    const status = getStatus(instance)
    const [lastChat, lastIteration, lastMessage] = getLastMessage(instance)
    const triggerReEvaluation = useCallback(async () => {
        const [success, error] = await reEvaluateInstance(instance)
        if (success) {
            const toastsId: { dismiss: () => void }[] = []
            for (let i = 0; i < 3; i++) {
                setTimeout(() => {
                    toastsId.push(toast({
                        title: "Re-evaluating...",
                        description: `The instance will be re-evaluated in ${3 - i} seconds`,
                    }))
                }, i * 1000)
            }
            setTimeout(() => {
                toastsId.forEach(toastId => toastId.dismiss())
                forceReload()
            }, 3000)
        } else {
            if (error)
                toast(error)
        }
    }, [instance])

    return (<ContextMenu>
        <ContextMenuTrigger>
            {children}
        </ContextMenuTrigger>
        <ContextMenuContent>
            <ContextMenuItem disabled={(status !== InstanceStatus.DONE || !lastMessage) ? true : undefined}
                onClick={triggerReEvaluation}
                className="space-x-2"
            >
                <RotateCcwIcon className="size-4" /> <p>Re-Evaluate </p>
            </ContextMenuItem>
            <ContextMenuSeparator />
            <ContextMenuItem
                className="space-x-2"
                disabled={!lastMessage ? true : undefined}
                onClick={() => {
                    navigator.clipboard.writeText(lastMessage?.content ?? "")
                    toast({
                        title: "Copied to clipboard",
                        description: "The last message has been copied to the clipboard",
                    })
                }}
            >
                <ClipboardCopyIcon className="size-4" /> <p>Copy last message</p>
            </ContextMenuItem>
            <ContextMenuItem
                className="space-x-2"
                disabled={!data.evaluation ? true : undefined}
                onClick={() => {
                    const evaluation = JSON.parse(JSON.stringify(data.evaluation))
                    delete evaluation?.diagram
                
                    console.log("Evaluation", evaluation)
                    navigator.clipboard.writeText(JSON.stringify(evaluation) ?? "")
                    toast({
                        title: "Printed & Copied to clipboard",
                        description: "The evaluation has been printed and copied to the clipboard",
                    })
                }}
            >
                <ScrollTextIcon className="size-4" /> <p>Get last evaluation</p>
            </ContextMenuItem>
            <ContextMenuSeparator />
            <ContextMenuSub>
                <ContextMenuSubTrigger className="space-x-2"
                    disabled={!lastMessage || !(`score` in lastMessage) ? true : undefined}
                ><FileLineChartIcon className="size-4" /> <p>Export diagram</p></ContextMenuSubTrigger>
                <ContextMenuSubContent>
                    <ContextMenuItem
                        className="space-x-1"
                        onClick={() => {
                            try {
                                const content = getPlantUML(lastMessage?.content ?? "")
                                navigator.clipboard.writeText(content)
                                toast({
                                    title: "Copied to clipboard",
                                    description: "The diagram has been copied to the clipboard",
                                })
                            } catch (element) {
                                toast({
                                    title: "Error",
                                    description: "The diagram could not be copied to the clipboard",
                                    variant: "destructive"
                                })
                            }
                        }}
                    >
                        <ClipboardCopyIcon className="size-4" /> <p>To Clipboard</p>
                    </ContextMenuItem>
                    <ContextMenuItem
                        className="space-x-1"
                        onClick={() => {
                            try {
                                const url = generatePlantUMLLink(lastMessage?.content ?? "")
                                window.open(url, '_blank')
                            } catch (element) {
                                console.error(element)
                                toast({
                                    title: "Error",
                                    description: "The diagram could not be generated",
                                    variant: "destructive"
                                })
                            }
                        }}
                    >
                        <LinkIcon className="size-4" /> <p>To Web Editor</p>
                    </ContextMenuItem>
                </ContextMenuSubContent>
            </ContextMenuSub>
            <ContextMenuItem
                className="space-x-2"
                onClick={() => {
                    window.open(`/instances/${data.id}/transcript`, '_blank')
                }}
            >
                <BookTextIcon className="size-4" /> <p>Open transcript</p>
            </ContextMenuItem>

        </ContextMenuContent>
    </ContextMenu>)
}

